services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./volumes/grafana:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana

  eureka-server:
    build: infra/eureka-server
    image: eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    env_file:
      - .env
    networks:
      - spring
    depends_on:
      - zipkin

  api-gateway:
    build: infra/api-gateway
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "8083:8083"
    env_file:
      - .env
    networks:
      - spring
    depends_on:
      - zipkin
      - eureka-server

  article:
    build: article
    image: article:latest
    container_name: article
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - eureka-server

  comment:
    build: comment
    image: comment:latest
    container_name: comment
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - eureka-server
      - rabbitmq

  notification:
    build: notification
    image: notification:latest
    container_name: notification
    ports:
      - "8082:8082"
    env_file:
      - .env
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres
      - eureka-server
      - rabbitmq

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  db-data:
  grafana-data:
