server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/
    fetch-registry: true
    register-with-eureka: true
    enabled: false